name: doxygen-deploy

on:
  push:
    brnaches: [ master ]

jobs:
  deploy-groupwork:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install doxygen
      run: sudo apt-get install -y doxygen

    # Run doxygen
    - name: Run Doxygen
      working-directory: ${{github.workspace}}
      run: doxygen

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: ${{github.workspace}}/html